# Generated by Django 4.2.7 on 2025-11-15 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('session_type', models.CharField(choices=[('TRADING', 'Trading Session'), ('QNA', 'Q&A Session'), ('EDUCATION', 'Educational Session'), ('MARKET_ANALYSIS', 'Market Analysis')], default='TRADING', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('is_public', models.BooleanField(default=True)),
                ('room_id', models.CharField(help_text='Unique room identifier for WebRTC', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trader', models.ForeignKey(limit_choices_to={'userprofile__is_trader': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frontend_livesession',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_trader',
            field=models.BooleanField(default=False, help_text='Designates if this user is a trader who can host live sessions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_bio',
            field=models.TextField(blank=True, help_text="Trader's biography and expertise", null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_experience',
            field=models.CharField(blank=True, help_text='e.g., 5+ years in Forex', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_specialization',
            field=models.CharField(blank=True, help_text='e.g., Forex, Crypto, Stocks', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SessionTradeIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('idea_type', models.CharField(choices=[('BUY', 'Buy Recommendation'), ('SELL', 'Sell Recommendation'), ('HOLD', 'Hold Recommendation'), ('WATCH', 'Watchlist Addition')], max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rationale', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_ideas', to='frontend.livesession')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frontend_sessiontradeidea',
            },
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='frontend.livesession')),
            ],
            options={
                'db_table': 'frontend_sessionrecording',
            },
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('TEXT', 'Text Message'), ('TRADE_IDEA', 'Trade Idea'), ('ANNOUNCEMENT', 'Announcement'), ('QUESTION', 'Question'), ('ANSWER', 'Answer')], default='TEXT', max_length=15)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='frontend.sessionmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='frontend.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frontend_sessionmessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TRADER', 'Trader'), ('MODERATOR', 'Moderator'), ('PARTICIPANT', 'Participant'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=15)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='frontend.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frontend_sessionparticipant',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
