# Generated by Django 4.2.7 on 2025-11-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_livesession_userprofile_is_trader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trader_application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_application_feedback',
            field=models.TextField(blank=True, help_text='Feedback for rejected applications', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_application_status',
            field=models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_APPLIED', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trader_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
    ]
