# Generated by Django 4.2.26 on 2025-11-15 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0004_userprofile_bio_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief introduction about yourself (max 500 characters)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_participants',
            field=models.PositiveIntegerField(default=10, help_text='Maximum participants for video calls'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_markets',
            field=models.CharField(blank=True, help_text='Preferred trading markets (e.g., Forex, Crypto, Stocks)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='successful_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_trades',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trader_bio',
            field=models.TextField(blank=True, help_text="Trader's biography and expertise (max 1000 characters)", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trader_experience',
            field=models.CharField(blank=True, help_text='e.g., 5+ years in Forex Trading', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trader_specialization',
            field=models.CharField(blank=True, help_text='e.g., Forex, Crypto, Stocks, Options', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
